[package]
name = "avast"
description = "AVaSt mod loader core, forked from Avast"
publish = false
version.workspace = true
edition.workspace = true
license.workspace = true

[dependencies]
filesilly.workspace = true
avast-godot.workspace = true
tracing.workspace = true
tracing-subscriber.workspace = true
tracing-appender.workspace = true
tracing-error.workspace = true
serde.workspace = true
serde_json.workspace = true
figment.workspace = true
toml.workspace = true
toml_edit.workspace = true
documented.workspace = true
memmap2.workspace = true
parking_lot.workspace = true
indexmap.workspace = true
zip.workspace = true
ordered-float.workspace = true
include_dir.workspace = true
color-eyre.workspace = true
